---
driver:
  name: gce
  project: dazzlingwrench
  region: us-east1
  preemptible: true
  metadata:
    ssh-keys: <%= 'kitchenuser:' + IO.binread("/tmp/id_rsa.pub").rstrip! %>
  tags:
  - fxinnovation

provisioner:
  name: chef_zero

verifier:
  name: inspec
  sudo: true
  format: junit
  output: "%{platform}_%{suite}_inspec.xml"

transport:
  username: kitchenuser
  ssh_key: /tmp/id_rsa

platforms:
  - name: centos6
    driver:
      image_project: centos-cloud
      image_family: centos-6
  - name: centos7
    driver:
      image_project: centos-cloud
      image_family: centos-7
  - name: ubuntu1404
    driver:
      image_project: ubuntu-cloud
      image_family: ubuntu-1404-lts
  - name: ubuntu1604
    driver:
      image_project: ubuntu-cloud
      image_family: ubuntu-1604-lts

suites:
  - name: default
    run_list:
      - recipe[pam_radius::kitchen]
    attributes:
      pam_radius:
        configuration:
        - host: radius.internal
          port: 12345
          shared_secret: supersecret
          timeout: 5
          source_ip: 10.0.0.1
    verifier:
      inspec_tests:
      - name: default
        path: test/integration/default
